name: CI tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Maven Wrapper Validation
        run: ./mvnw -v

      - name: Run Unit Tests
        run: ./mvnw -B clean test

      - name: Package (skip tests)
        if: success()
        run: ./mvnw -B package -DskipTests

      - name: Upload Surefire Reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
          if-no-files-found: ignore
